//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMix.Client.ViajeHttps {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://carmix.viaje.admin/", ConfigurationName="ViajeHttps.WebService_ViajeSoap")]
    public interface WebService_ViajeSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ViajesRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/Viajes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.ViajeHttps.ViajesResponse Viajes(CarMix.Client.ViajeHttps.ViajesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/Viajes", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.ViajesResponse> ViajesAsync(CarMix.Client.ViajeHttps.ViajesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje AddViajeRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/AddViaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.ViajeHttps.AddViajeResponse AddViaje(CarMix.Client.ViajeHttps.AddViajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/AddViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.AddViajeResponse> AddViajeAsync(CarMix.Client.ViajeHttps.AddViajeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje DeleteViajeRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/DeleteViaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.ViajeHttps.DeleteViajeResponse DeleteViaje(CarMix.Client.ViajeHttps.DeleteViajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/DeleteViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.DeleteViajeResponse> DeleteViajeAsync(CarMix.Client.ViajeHttps.DeleteViajeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje UpdateViajeRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/UpdateViaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.ViajeHttps.UpdateViajeResponse UpdateViaje(CarMix.Client.ViajeHttps.UpdateViajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/UpdateViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.UpdateViajeResponse> UpdateViajeAsync(CarMix.Client.ViajeHttps.UpdateViajeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje FindViajeRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/FindViaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.ViajeHttps.FindViajeResponse FindViaje(CarMix.Client.ViajeHttps.FindViajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/FindViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.FindViajeResponse> FindViajeAsync(CarMix.Client.ViajeHttps.FindViajeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje DestinosPopularesRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/DestinosPopulares", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.ViajeHttps.DestinosPopularesResponse DestinosPopulares(CarMix.Client.ViajeHttps.DestinosPopularesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/DestinosPopulares", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.DestinosPopularesResponse> DestinosPopularesAsync(CarMix.Client.ViajeHttps.DestinosPopularesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje OrigenesPopularesRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/OrigenesPopulares", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.ViajeHttps.OrigenesPopularesResponse OrigenesPopulares(CarMix.Client.ViajeHttps.OrigenesPopularesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.viaje.admin/OrigenesPopulares", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.OrigenesPopularesResponse> OrigenesPopularesAsync(CarMix.Client.ViajeHttps.OrigenesPopularesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    public partial class Security : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://carmix.viaje.admin/")]
    public partial class LugaresPopulares : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long aparicionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Apariciones {
            get {
                return this.aparicionesField;
            }
            set {
                this.aparicionesField = value;
                this.RaisePropertyChanged("Apariciones");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://carmix.viaje.admin/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string passwordField;
        
        private string generoMusicalField;
        
        private Viaje[] viajesCreadosField;
        
        private Viaje[] viajesSuscritoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GeneroMusical {
            get {
                return this.generoMusicalField;
            }
            set {
                this.generoMusicalField = value;
                this.RaisePropertyChanged("GeneroMusical");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Viaje[] ViajesCreados {
            get {
                return this.viajesCreadosField;
            }
            set {
                this.viajesCreadosField = value;
                this.RaisePropertyChanged("ViajesCreados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Viaje[] ViajesSuscrito {
            get {
                return this.viajesSuscritoField;
            }
            set {
                this.viajesSuscritoField = value;
                this.RaisePropertyChanged("ViajesSuscrito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://carmix.viaje.admin/")]
    public partial class Viaje : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string origenField;
        
        private string destinoField;
        
        private int plazasField;
        
        private decimal precioField;
        
        private string descripcionField;
        
        private User[] invitadosField;
        
        private User creadorField;
        
        private string listaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
                this.RaisePropertyChanged("Origen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Plazas {
            get {
                return this.plazasField;
            }
            set {
                this.plazasField = value;
                this.RaisePropertyChanged("Plazas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("Precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public User[] Invitados {
            get {
                return this.invitadosField;
            }
            set {
                this.invitadosField = value;
                this.RaisePropertyChanged("Invitados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public User Creador {
            get {
                return this.creadorField;
            }
            set {
                this.creadorField = value;
                this.RaisePropertyChanged("Creador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("Lista");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Viajes", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class ViajesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.ViajeHttps.Security Security;
        
        public ViajesRequest() {
        }
        
        public ViajesRequest(CarMix.Client.ViajeHttps.Security Security) {
            this.Security = Security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ViajesResponse", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class ViajesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public CarMix.Client.ViajeHttps.Viaje[] ViajesResult;
        
        public ViajesResponse() {
        }
        
        public ViajesResponse(CarMix.Client.ViajeHttps.Viaje[] ViajesResult) {
            this.ViajesResult = ViajesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddViaje", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class AddViajeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.ViajeHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public long idCreador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=1)]
        public string origen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=2)]
        public string destino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=3)]
        public int plazas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=4)]
        public decimal precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=5)]
        public string descripcion;
        
        public AddViajeRequest() {
        }
        
        public AddViajeRequest(CarMix.Client.ViajeHttps.Security Security, long idCreador, string origen, string destino, int plazas, decimal precio, string descripcion) {
            this.Security = Security;
            this.idCreador = idCreador;
            this.origen = origen;
            this.destino = destino;
            this.plazas = plazas;
            this.precio = precio;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddViajeResponse", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class AddViajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public string AddViajeResult;
        
        public AddViajeResponse() {
        }
        
        public AddViajeResponse(string AddViajeResult) {
            this.AddViajeResult = AddViajeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteViaje", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class DeleteViajeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.ViajeHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public long id;
        
        public DeleteViajeRequest() {
        }
        
        public DeleteViajeRequest(CarMix.Client.ViajeHttps.Security Security, long id) {
            this.Security = Security;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteViajeResponse", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class DeleteViajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public string DeleteViajeResult;
        
        public DeleteViajeResponse() {
        }
        
        public DeleteViajeResponse(string DeleteViajeResult) {
            this.DeleteViajeResult = DeleteViajeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateViaje", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class UpdateViajeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.ViajeHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=1)]
        public string origen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=2)]
        public string destino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=3)]
        public int plazas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=4)]
        public decimal precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=5)]
        public string descripcion;
        
        public UpdateViajeRequest() {
        }
        
        public UpdateViajeRequest(CarMix.Client.ViajeHttps.Security Security, int id, string origen, string destino, int plazas, decimal precio, string descripcion) {
            this.Security = Security;
            this.id = id;
            this.origen = origen;
            this.destino = destino;
            this.plazas = plazas;
            this.precio = precio;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateViajeResponse", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class UpdateViajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public string UpdateViajeResult;
        
        public UpdateViajeResponse() {
        }
        
        public UpdateViajeResponse(string UpdateViajeResult) {
            this.UpdateViajeResult = UpdateViajeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindViaje", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class FindViajeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.ViajeHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public int id;
        
        public FindViajeRequest() {
        }
        
        public FindViajeRequest(CarMix.Client.ViajeHttps.Security Security, int id) {
            this.Security = Security;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindViajeResponse", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class FindViajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public CarMix.Client.ViajeHttps.Viaje FindViajeResult;
        
        public FindViajeResponse() {
        }
        
        public FindViajeResponse(CarMix.Client.ViajeHttps.Viaje FindViajeResult) {
            this.FindViajeResult = FindViajeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DestinosPopulares", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class DestinosPopularesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.ViajeHttps.Security Security;
        
        public DestinosPopularesRequest() {
        }
        
        public DestinosPopularesRequest(CarMix.Client.ViajeHttps.Security Security) {
            this.Security = Security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DestinosPopularesResponse", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class DestinosPopularesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public CarMix.Client.ViajeHttps.LugaresPopulares[] DestinosPopularesResult;
        
        public DestinosPopularesResponse() {
        }
        
        public DestinosPopularesResponse(CarMix.Client.ViajeHttps.LugaresPopulares[] DestinosPopularesResult) {
            this.DestinosPopularesResult = DestinosPopularesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrigenesPopulares", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class OrigenesPopularesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.ViajeHttps.Security Security;
        
        public OrigenesPopularesRequest() {
        }
        
        public OrigenesPopularesRequest(CarMix.Client.ViajeHttps.Security Security) {
            this.Security = Security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrigenesPopularesResponse", WrapperNamespace="http://carmix.viaje.admin/", IsWrapped=true)]
    public partial class OrigenesPopularesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.viaje.admin/", Order=0)]
        public CarMix.Client.ViajeHttps.LugaresPopulares[] OrigenesPopularesResult;
        
        public OrigenesPopularesResponse() {
        }
        
        public OrigenesPopularesResponse(CarMix.Client.ViajeHttps.LugaresPopulares[] OrigenesPopularesResult) {
            this.OrigenesPopularesResult = OrigenesPopularesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_ViajeSoapChannel : CarMix.Client.ViajeHttps.WebService_ViajeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_ViajeSoapClient : System.ServiceModel.ClientBase<CarMix.Client.ViajeHttps.WebService_ViajeSoap>, CarMix.Client.ViajeHttps.WebService_ViajeSoap {
        
        public WebService_ViajeSoapClient() {
        }
        
        public WebService_ViajeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_ViajeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ViajeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ViajeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.ViajeHttps.ViajesResponse CarMix.Client.ViajeHttps.WebService_ViajeSoap.Viajes(CarMix.Client.ViajeHttps.ViajesRequest request) {
            return base.Channel.Viajes(request);
        }
        
        public CarMix.Client.ViajeHttps.Viaje[] Viajes(CarMix.Client.ViajeHttps.Security Security) {
            CarMix.Client.ViajeHttps.ViajesRequest inValue = new CarMix.Client.ViajeHttps.ViajesRequest();
            inValue.Security = Security;
            CarMix.Client.ViajeHttps.ViajesResponse retVal = ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).Viajes(inValue);
            return retVal.ViajesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.ViajesResponse> CarMix.Client.ViajeHttps.WebService_ViajeSoap.ViajesAsync(CarMix.Client.ViajeHttps.ViajesRequest request) {
            return base.Channel.ViajesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.ViajesResponse> ViajesAsync(CarMix.Client.ViajeHttps.Security Security) {
            CarMix.Client.ViajeHttps.ViajesRequest inValue = new CarMix.Client.ViajeHttps.ViajesRequest();
            inValue.Security = Security;
            return ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).ViajesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.ViajeHttps.AddViajeResponse CarMix.Client.ViajeHttps.WebService_ViajeSoap.AddViaje(CarMix.Client.ViajeHttps.AddViajeRequest request) {
            return base.Channel.AddViaje(request);
        }
        
        public string AddViaje(CarMix.Client.ViajeHttps.Security Security, long idCreador, string origen, string destino, int plazas, decimal precio, string descripcion) {
            CarMix.Client.ViajeHttps.AddViajeRequest inValue = new CarMix.Client.ViajeHttps.AddViajeRequest();
            inValue.Security = Security;
            inValue.idCreador = idCreador;
            inValue.origen = origen;
            inValue.destino = destino;
            inValue.plazas = plazas;
            inValue.precio = precio;
            inValue.descripcion = descripcion;
            CarMix.Client.ViajeHttps.AddViajeResponse retVal = ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).AddViaje(inValue);
            return retVal.AddViajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.AddViajeResponse> CarMix.Client.ViajeHttps.WebService_ViajeSoap.AddViajeAsync(CarMix.Client.ViajeHttps.AddViajeRequest request) {
            return base.Channel.AddViajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.AddViajeResponse> AddViajeAsync(CarMix.Client.ViajeHttps.Security Security, long idCreador, string origen, string destino, int plazas, decimal precio, string descripcion) {
            CarMix.Client.ViajeHttps.AddViajeRequest inValue = new CarMix.Client.ViajeHttps.AddViajeRequest();
            inValue.Security = Security;
            inValue.idCreador = idCreador;
            inValue.origen = origen;
            inValue.destino = destino;
            inValue.plazas = plazas;
            inValue.precio = precio;
            inValue.descripcion = descripcion;
            return ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).AddViajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.ViajeHttps.DeleteViajeResponse CarMix.Client.ViajeHttps.WebService_ViajeSoap.DeleteViaje(CarMix.Client.ViajeHttps.DeleteViajeRequest request) {
            return base.Channel.DeleteViaje(request);
        }
        
        public string DeleteViaje(CarMix.Client.ViajeHttps.Security Security, long id) {
            CarMix.Client.ViajeHttps.DeleteViajeRequest inValue = new CarMix.Client.ViajeHttps.DeleteViajeRequest();
            inValue.Security = Security;
            inValue.id = id;
            CarMix.Client.ViajeHttps.DeleteViajeResponse retVal = ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).DeleteViaje(inValue);
            return retVal.DeleteViajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.DeleteViajeResponse> CarMix.Client.ViajeHttps.WebService_ViajeSoap.DeleteViajeAsync(CarMix.Client.ViajeHttps.DeleteViajeRequest request) {
            return base.Channel.DeleteViajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.DeleteViajeResponse> DeleteViajeAsync(CarMix.Client.ViajeHttps.Security Security, long id) {
            CarMix.Client.ViajeHttps.DeleteViajeRequest inValue = new CarMix.Client.ViajeHttps.DeleteViajeRequest();
            inValue.Security = Security;
            inValue.id = id;
            return ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).DeleteViajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.ViajeHttps.UpdateViajeResponse CarMix.Client.ViajeHttps.WebService_ViajeSoap.UpdateViaje(CarMix.Client.ViajeHttps.UpdateViajeRequest request) {
            return base.Channel.UpdateViaje(request);
        }
        
        public string UpdateViaje(CarMix.Client.ViajeHttps.Security Security, int id, string origen, string destino, int plazas, decimal precio, string descripcion) {
            CarMix.Client.ViajeHttps.UpdateViajeRequest inValue = new CarMix.Client.ViajeHttps.UpdateViajeRequest();
            inValue.Security = Security;
            inValue.id = id;
            inValue.origen = origen;
            inValue.destino = destino;
            inValue.plazas = plazas;
            inValue.precio = precio;
            inValue.descripcion = descripcion;
            CarMix.Client.ViajeHttps.UpdateViajeResponse retVal = ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).UpdateViaje(inValue);
            return retVal.UpdateViajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.UpdateViajeResponse> CarMix.Client.ViajeHttps.WebService_ViajeSoap.UpdateViajeAsync(CarMix.Client.ViajeHttps.UpdateViajeRequest request) {
            return base.Channel.UpdateViajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.UpdateViajeResponse> UpdateViajeAsync(CarMix.Client.ViajeHttps.Security Security, int id, string origen, string destino, int plazas, decimal precio, string descripcion) {
            CarMix.Client.ViajeHttps.UpdateViajeRequest inValue = new CarMix.Client.ViajeHttps.UpdateViajeRequest();
            inValue.Security = Security;
            inValue.id = id;
            inValue.origen = origen;
            inValue.destino = destino;
            inValue.plazas = plazas;
            inValue.precio = precio;
            inValue.descripcion = descripcion;
            return ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).UpdateViajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.ViajeHttps.FindViajeResponse CarMix.Client.ViajeHttps.WebService_ViajeSoap.FindViaje(CarMix.Client.ViajeHttps.FindViajeRequest request) {
            return base.Channel.FindViaje(request);
        }
        
        public CarMix.Client.ViajeHttps.Viaje FindViaje(CarMix.Client.ViajeHttps.Security Security, int id) {
            CarMix.Client.ViajeHttps.FindViajeRequest inValue = new CarMix.Client.ViajeHttps.FindViajeRequest();
            inValue.Security = Security;
            inValue.id = id;
            CarMix.Client.ViajeHttps.FindViajeResponse retVal = ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).FindViaje(inValue);
            return retVal.FindViajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.FindViajeResponse> CarMix.Client.ViajeHttps.WebService_ViajeSoap.FindViajeAsync(CarMix.Client.ViajeHttps.FindViajeRequest request) {
            return base.Channel.FindViajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.FindViajeResponse> FindViajeAsync(CarMix.Client.ViajeHttps.Security Security, int id) {
            CarMix.Client.ViajeHttps.FindViajeRequest inValue = new CarMix.Client.ViajeHttps.FindViajeRequest();
            inValue.Security = Security;
            inValue.id = id;
            return ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).FindViajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.ViajeHttps.DestinosPopularesResponse CarMix.Client.ViajeHttps.WebService_ViajeSoap.DestinosPopulares(CarMix.Client.ViajeHttps.DestinosPopularesRequest request) {
            return base.Channel.DestinosPopulares(request);
        }
        
        public CarMix.Client.ViajeHttps.LugaresPopulares[] DestinosPopulares(CarMix.Client.ViajeHttps.Security Security) {
            CarMix.Client.ViajeHttps.DestinosPopularesRequest inValue = new CarMix.Client.ViajeHttps.DestinosPopularesRequest();
            inValue.Security = Security;
            CarMix.Client.ViajeHttps.DestinosPopularesResponse retVal = ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).DestinosPopulares(inValue);
            return retVal.DestinosPopularesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.DestinosPopularesResponse> CarMix.Client.ViajeHttps.WebService_ViajeSoap.DestinosPopularesAsync(CarMix.Client.ViajeHttps.DestinosPopularesRequest request) {
            return base.Channel.DestinosPopularesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.DestinosPopularesResponse> DestinosPopularesAsync(CarMix.Client.ViajeHttps.Security Security) {
            CarMix.Client.ViajeHttps.DestinosPopularesRequest inValue = new CarMix.Client.ViajeHttps.DestinosPopularesRequest();
            inValue.Security = Security;
            return ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).DestinosPopularesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.ViajeHttps.OrigenesPopularesResponse CarMix.Client.ViajeHttps.WebService_ViajeSoap.OrigenesPopulares(CarMix.Client.ViajeHttps.OrigenesPopularesRequest request) {
            return base.Channel.OrigenesPopulares(request);
        }
        
        public CarMix.Client.ViajeHttps.LugaresPopulares[] OrigenesPopulares(CarMix.Client.ViajeHttps.Security Security) {
            CarMix.Client.ViajeHttps.OrigenesPopularesRequest inValue = new CarMix.Client.ViajeHttps.OrigenesPopularesRequest();
            inValue.Security = Security;
            CarMix.Client.ViajeHttps.OrigenesPopularesResponse retVal = ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).OrigenesPopulares(inValue);
            return retVal.OrigenesPopularesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.OrigenesPopularesResponse> CarMix.Client.ViajeHttps.WebService_ViajeSoap.OrigenesPopularesAsync(CarMix.Client.ViajeHttps.OrigenesPopularesRequest request) {
            return base.Channel.OrigenesPopularesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.ViajeHttps.OrigenesPopularesResponse> OrigenesPopularesAsync(CarMix.Client.ViajeHttps.Security Security) {
            CarMix.Client.ViajeHttps.OrigenesPopularesRequest inValue = new CarMix.Client.ViajeHttps.OrigenesPopularesRequest();
            inValue.Security = Security;
            return ((CarMix.Client.ViajeHttps.WebService_ViajeSoap)(this)).OrigenesPopularesAsync(inValue);
        }
    }
}
