//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMix.Client.UserHttps {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://carmix.user.admin/", ConfigurationName="UserHttps.WebService_UserSoap")]
    public interface WebService_UserSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje UsersRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/Users", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.UsersResponse Users(CarMix.Client.UserHttps.UsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/Users", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.UsersResponse> UsersAsync(CarMix.Client.UserHttps.UsersRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje AddUserRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/AddUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.AddUserResponse AddUser(CarMix.Client.UserHttps.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.AddUserResponse> AddUserAsync(CarMix.Client.UserHttps.AddUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje DeleteUserRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/DeleteUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.DeleteUserResponse DeleteUser(CarMix.Client.UserHttps.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteUserResponse> DeleteUserAsync(CarMix.Client.UserHttps.DeleteUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ChangePasswordRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.ChangePasswordResponse ChangePassword(CarMix.Client.UserHttps.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.ChangePasswordResponse> ChangePasswordAsync(CarMix.Client.UserHttps.ChangePasswordRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje UpdateUserRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/UpdateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.UpdateUserResponse UpdateUser(CarMix.Client.UserHttps.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.UpdateUserResponse> UpdateUserAsync(CarMix.Client.UserHttps.UpdateUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje FindUserRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/FindUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.FindUserResponse FindUser(CarMix.Client.UserHttps.FindUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/FindUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.FindUserResponse> FindUserAsync(CarMix.Client.UserHttps.FindUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje UsersActivityRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/UsersActivity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.UsersActivityResponse UsersActivity(CarMix.Client.UserHttps.UsersActivityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/UsersActivity", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.UsersActivityResponse> UsersActivityAsync(CarMix.Client.UserHttps.UsersActivityRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje DeleteInvitadoRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/DeleteInvitado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.DeleteInvitadoResponse DeleteInvitado(CarMix.Client.UserHttps.DeleteInvitadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/DeleteInvitado", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteInvitadoResponse> DeleteInvitadoAsync(CarMix.Client.UserHttps.DeleteInvitadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje DeleteViajesUserRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/DeleteViajesUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarMix.Client.UserHttps.DeleteViajesUserResponse DeleteViajesUser(CarMix.Client.UserHttps.DeleteViajesUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://carmix.user.admin/DeleteViajesUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteViajesUserResponse> DeleteViajesUserAsync(CarMix.Client.UserHttps.DeleteViajesUserRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    public partial class Security : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://carmix.user.admin/")]
    public partial class UserActivity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private long aparicionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Apariciones {
            get {
                return this.aparicionesField;
            }
            set {
                this.aparicionesField = value;
                this.RaisePropertyChanged("Apariciones");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://carmix.user.admin/")]
    public partial class Viaje : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string origenField;
        
        private string destinoField;
        
        private int plazasField;
        
        private decimal precioField;
        
        private string descripcionField;
        
        private User[] invitadosField;
        
        private User creadorField;
        
        private string listaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
                this.RaisePropertyChanged("Origen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Plazas {
            get {
                return this.plazasField;
            }
            set {
                this.plazasField = value;
                this.RaisePropertyChanged("Plazas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("Precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public User[] Invitados {
            get {
                return this.invitadosField;
            }
            set {
                this.invitadosField = value;
                this.RaisePropertyChanged("Invitados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public User Creador {
            get {
                return this.creadorField;
            }
            set {
                this.creadorField = value;
                this.RaisePropertyChanged("Creador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("Lista");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://carmix.user.admin/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string passwordField;
        
        private string generoMusicalField;
        
        private Viaje[] viajesCreadosField;
        
        private Viaje[] viajesSuscritoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GeneroMusical {
            get {
                return this.generoMusicalField;
            }
            set {
                this.generoMusicalField = value;
                this.RaisePropertyChanged("GeneroMusical");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Viaje[] ViajesCreados {
            get {
                return this.viajesCreadosField;
            }
            set {
                this.viajesCreadosField = value;
                this.RaisePropertyChanged("ViajesCreados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Viaje[] ViajesSuscrito {
            get {
                return this.viajesSuscritoField;
            }
            set {
                this.viajesSuscritoField = value;
                this.RaisePropertyChanged("ViajesSuscrito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Users", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class UsersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        public UsersRequest() {
        }
        
        public UsersRequest(CarMix.Client.UserHttps.Security Security) {
            this.Security = Security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsersResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class UsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public CarMix.Client.UserHttps.User[] UsersResult;
        
        public UsersResponse() {
        }
        
        public UsersResponse(CarMix.Client.UserHttps.User[] UsersResult) {
            this.UsersResult = UsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUser", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=2)]
        public string generoMusical;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(CarMix.Client.UserHttps.Security Security, string name, string password, string generoMusical) {
            this.Security = Security;
            this.name = name;
            this.password = password;
            this.generoMusical = generoMusical;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public string AddUserResult;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(string AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUser", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public int id;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(CarMix.Client.UserHttps.Security Security, int id) {
            this.Security = Security;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUserResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public string DeleteUserResult;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(string DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=1)]
        public string password;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(CarMix.Client.UserHttps.Security Security, int id, string password) {
            this.Security = Security;
            this.id = id;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public string ChangePasswordResult;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(string ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUser", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=3)]
        public string gustosMusicales;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(CarMix.Client.UserHttps.Security Security, int id, string name, string password, string gustosMusicales) {
            this.Security = Security;
            this.id = id;
            this.name = name;
            this.password = password;
            this.gustosMusicales = gustosMusicales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public string UpdateUserResult;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(string UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUser", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class FindUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public int id;
        
        public FindUserRequest() {
        }
        
        public FindUserRequest(CarMix.Client.UserHttps.Security Security, int id) {
            this.Security = Security;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class FindUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public CarMix.Client.UserHttps.User FindUserResult;
        
        public FindUserResponse() {
        }
        
        public FindUserResponse(CarMix.Client.UserHttps.User FindUserResult) {
            this.FindUserResult = FindUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsersActivity", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class UsersActivityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        public UsersActivityRequest() {
        }
        
        public UsersActivityRequest(CarMix.Client.UserHttps.Security Security) {
            this.Security = Security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsersActivityResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class UsersActivityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public CarMix.Client.UserHttps.UserActivity[] UsersActivityResult;
        
        public UsersActivityResponse() {
        }
        
        public UsersActivityResponse(CarMix.Client.UserHttps.UserActivity[] UsersActivityResult) {
            this.UsersActivityResult = UsersActivityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteInvitado", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class DeleteInvitadoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public long id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=1)]
        public long idViaje;
        
        public DeleteInvitadoRequest() {
        }
        
        public DeleteInvitadoRequest(CarMix.Client.UserHttps.Security Security, long id, long idViaje) {
            this.Security = Security;
            this.id = id;
            this.idViaje = idViaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteInvitadoResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class DeleteInvitadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public string DeleteInvitadoResult;
        
        public DeleteInvitadoResponse() {
        }
        
        public DeleteInvitadoResponse(string DeleteInvitadoResult) {
            this.DeleteInvitadoResult = DeleteInvitadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteViajesUser", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class DeleteViajesUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public CarMix.Client.UserHttps.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public int id;
        
        public DeleteViajesUserRequest() {
        }
        
        public DeleteViajesUserRequest(CarMix.Client.UserHttps.Security Security, int id) {
            this.Security = Security;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteViajesUserResponse", WrapperNamespace="http://carmix.user.admin/", IsWrapped=true)]
    public partial class DeleteViajesUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://carmix.user.admin/", Order=0)]
        public string DeleteViajesUserResult;
        
        public DeleteViajesUserResponse() {
        }
        
        public DeleteViajesUserResponse(string DeleteViajesUserResult) {
            this.DeleteViajesUserResult = DeleteViajesUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_UserSoapChannel : CarMix.Client.UserHttps.WebService_UserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_UserSoapClient : System.ServiceModel.ClientBase<CarMix.Client.UserHttps.WebService_UserSoap>, CarMix.Client.UserHttps.WebService_UserSoap {
        
        public WebService_UserSoapClient() {
        }
        
        public WebService_UserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_UserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_UserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_UserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.UsersResponse CarMix.Client.UserHttps.WebService_UserSoap.Users(CarMix.Client.UserHttps.UsersRequest request) {
            return base.Channel.Users(request);
        }
        
        public CarMix.Client.UserHttps.User[] Users(CarMix.Client.UserHttps.Security Security) {
            CarMix.Client.UserHttps.UsersRequest inValue = new CarMix.Client.UserHttps.UsersRequest();
            inValue.Security = Security;
            CarMix.Client.UserHttps.UsersResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).Users(inValue);
            return retVal.UsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.UsersResponse> CarMix.Client.UserHttps.WebService_UserSoap.UsersAsync(CarMix.Client.UserHttps.UsersRequest request) {
            return base.Channel.UsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.UsersResponse> UsersAsync(CarMix.Client.UserHttps.Security Security) {
            CarMix.Client.UserHttps.UsersRequest inValue = new CarMix.Client.UserHttps.UsersRequest();
            inValue.Security = Security;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).UsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.AddUserResponse CarMix.Client.UserHttps.WebService_UserSoap.AddUser(CarMix.Client.UserHttps.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public string AddUser(CarMix.Client.UserHttps.Security Security, string name, string password, string generoMusical) {
            CarMix.Client.UserHttps.AddUserRequest inValue = new CarMix.Client.UserHttps.AddUserRequest();
            inValue.Security = Security;
            inValue.name = name;
            inValue.password = password;
            inValue.generoMusical = generoMusical;
            CarMix.Client.UserHttps.AddUserResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).AddUser(inValue);
            return retVal.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.AddUserResponse> CarMix.Client.UserHttps.WebService_UserSoap.AddUserAsync(CarMix.Client.UserHttps.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.AddUserResponse> AddUserAsync(CarMix.Client.UserHttps.Security Security, string name, string password, string generoMusical) {
            CarMix.Client.UserHttps.AddUserRequest inValue = new CarMix.Client.UserHttps.AddUserRequest();
            inValue.Security = Security;
            inValue.name = name;
            inValue.password = password;
            inValue.generoMusical = generoMusical;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.DeleteUserResponse CarMix.Client.UserHttps.WebService_UserSoap.DeleteUser(CarMix.Client.UserHttps.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public string DeleteUser(CarMix.Client.UserHttps.Security Security, int id) {
            CarMix.Client.UserHttps.DeleteUserRequest inValue = new CarMix.Client.UserHttps.DeleteUserRequest();
            inValue.Security = Security;
            inValue.id = id;
            CarMix.Client.UserHttps.DeleteUserResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).DeleteUser(inValue);
            return retVal.DeleteUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteUserResponse> CarMix.Client.UserHttps.WebService_UserSoap.DeleteUserAsync(CarMix.Client.UserHttps.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteUserResponse> DeleteUserAsync(CarMix.Client.UserHttps.Security Security, int id) {
            CarMix.Client.UserHttps.DeleteUserRequest inValue = new CarMix.Client.UserHttps.DeleteUserRequest();
            inValue.Security = Security;
            inValue.id = id;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.ChangePasswordResponse CarMix.Client.UserHttps.WebService_UserSoap.ChangePassword(CarMix.Client.UserHttps.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public string ChangePassword(CarMix.Client.UserHttps.Security Security, int id, string password) {
            CarMix.Client.UserHttps.ChangePasswordRequest inValue = new CarMix.Client.UserHttps.ChangePasswordRequest();
            inValue.Security = Security;
            inValue.id = id;
            inValue.password = password;
            CarMix.Client.UserHttps.ChangePasswordResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).ChangePassword(inValue);
            return retVal.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.ChangePasswordResponse> CarMix.Client.UserHttps.WebService_UserSoap.ChangePasswordAsync(CarMix.Client.UserHttps.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.ChangePasswordResponse> ChangePasswordAsync(CarMix.Client.UserHttps.Security Security, int id, string password) {
            CarMix.Client.UserHttps.ChangePasswordRequest inValue = new CarMix.Client.UserHttps.ChangePasswordRequest();
            inValue.Security = Security;
            inValue.id = id;
            inValue.password = password;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.UpdateUserResponse CarMix.Client.UserHttps.WebService_UserSoap.UpdateUser(CarMix.Client.UserHttps.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public string UpdateUser(CarMix.Client.UserHttps.Security Security, int id, string name, string password, string gustosMusicales) {
            CarMix.Client.UserHttps.UpdateUserRequest inValue = new CarMix.Client.UserHttps.UpdateUserRequest();
            inValue.Security = Security;
            inValue.id = id;
            inValue.name = name;
            inValue.password = password;
            inValue.gustosMusicales = gustosMusicales;
            CarMix.Client.UserHttps.UpdateUserResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).UpdateUser(inValue);
            return retVal.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.UpdateUserResponse> CarMix.Client.UserHttps.WebService_UserSoap.UpdateUserAsync(CarMix.Client.UserHttps.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.UpdateUserResponse> UpdateUserAsync(CarMix.Client.UserHttps.Security Security, int id, string name, string password, string gustosMusicales) {
            CarMix.Client.UserHttps.UpdateUserRequest inValue = new CarMix.Client.UserHttps.UpdateUserRequest();
            inValue.Security = Security;
            inValue.id = id;
            inValue.name = name;
            inValue.password = password;
            inValue.gustosMusicales = gustosMusicales;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).UpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.FindUserResponse CarMix.Client.UserHttps.WebService_UserSoap.FindUser(CarMix.Client.UserHttps.FindUserRequest request) {
            return base.Channel.FindUser(request);
        }
        
        public CarMix.Client.UserHttps.User FindUser(CarMix.Client.UserHttps.Security Security, int id) {
            CarMix.Client.UserHttps.FindUserRequest inValue = new CarMix.Client.UserHttps.FindUserRequest();
            inValue.Security = Security;
            inValue.id = id;
            CarMix.Client.UserHttps.FindUserResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).FindUser(inValue);
            return retVal.FindUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.FindUserResponse> CarMix.Client.UserHttps.WebService_UserSoap.FindUserAsync(CarMix.Client.UserHttps.FindUserRequest request) {
            return base.Channel.FindUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.FindUserResponse> FindUserAsync(CarMix.Client.UserHttps.Security Security, int id) {
            CarMix.Client.UserHttps.FindUserRequest inValue = new CarMix.Client.UserHttps.FindUserRequest();
            inValue.Security = Security;
            inValue.id = id;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).FindUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.UsersActivityResponse CarMix.Client.UserHttps.WebService_UserSoap.UsersActivity(CarMix.Client.UserHttps.UsersActivityRequest request) {
            return base.Channel.UsersActivity(request);
        }
        
        public CarMix.Client.UserHttps.UserActivity[] UsersActivity(CarMix.Client.UserHttps.Security Security) {
            CarMix.Client.UserHttps.UsersActivityRequest inValue = new CarMix.Client.UserHttps.UsersActivityRequest();
            inValue.Security = Security;
            CarMix.Client.UserHttps.UsersActivityResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).UsersActivity(inValue);
            return retVal.UsersActivityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.UsersActivityResponse> CarMix.Client.UserHttps.WebService_UserSoap.UsersActivityAsync(CarMix.Client.UserHttps.UsersActivityRequest request) {
            return base.Channel.UsersActivityAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.UsersActivityResponse> UsersActivityAsync(CarMix.Client.UserHttps.Security Security) {
            CarMix.Client.UserHttps.UsersActivityRequest inValue = new CarMix.Client.UserHttps.UsersActivityRequest();
            inValue.Security = Security;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).UsersActivityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.DeleteInvitadoResponse CarMix.Client.UserHttps.WebService_UserSoap.DeleteInvitado(CarMix.Client.UserHttps.DeleteInvitadoRequest request) {
            return base.Channel.DeleteInvitado(request);
        }
        
        public string DeleteInvitado(CarMix.Client.UserHttps.Security Security, long id, long idViaje) {
            CarMix.Client.UserHttps.DeleteInvitadoRequest inValue = new CarMix.Client.UserHttps.DeleteInvitadoRequest();
            inValue.Security = Security;
            inValue.id = id;
            inValue.idViaje = idViaje;
            CarMix.Client.UserHttps.DeleteInvitadoResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).DeleteInvitado(inValue);
            return retVal.DeleteInvitadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteInvitadoResponse> CarMix.Client.UserHttps.WebService_UserSoap.DeleteInvitadoAsync(CarMix.Client.UserHttps.DeleteInvitadoRequest request) {
            return base.Channel.DeleteInvitadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteInvitadoResponse> DeleteInvitadoAsync(CarMix.Client.UserHttps.Security Security, long id, long idViaje) {
            CarMix.Client.UserHttps.DeleteInvitadoRequest inValue = new CarMix.Client.UserHttps.DeleteInvitadoRequest();
            inValue.Security = Security;
            inValue.id = id;
            inValue.idViaje = idViaje;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).DeleteInvitadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarMix.Client.UserHttps.DeleteViajesUserResponse CarMix.Client.UserHttps.WebService_UserSoap.DeleteViajesUser(CarMix.Client.UserHttps.DeleteViajesUserRequest request) {
            return base.Channel.DeleteViajesUser(request);
        }
        
        public string DeleteViajesUser(CarMix.Client.UserHttps.Security Security, int id) {
            CarMix.Client.UserHttps.DeleteViajesUserRequest inValue = new CarMix.Client.UserHttps.DeleteViajesUserRequest();
            inValue.Security = Security;
            inValue.id = id;
            CarMix.Client.UserHttps.DeleteViajesUserResponse retVal = ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).DeleteViajesUser(inValue);
            return retVal.DeleteViajesUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteViajesUserResponse> CarMix.Client.UserHttps.WebService_UserSoap.DeleteViajesUserAsync(CarMix.Client.UserHttps.DeleteViajesUserRequest request) {
            return base.Channel.DeleteViajesUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarMix.Client.UserHttps.DeleteViajesUserResponse> DeleteViajesUserAsync(CarMix.Client.UserHttps.Security Security, int id) {
            CarMix.Client.UserHttps.DeleteViajesUserRequest inValue = new CarMix.Client.UserHttps.DeleteViajesUserRequest();
            inValue.Security = Security;
            inValue.id = id;
            return ((CarMix.Client.UserHttps.WebService_UserSoap)(this)).DeleteViajesUserAsync(inValue);
        }
    }
}
